CREATE TABLE public.employee_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_code VARCHAR(255) NOT NULL,
    document_type VARCHAR(255) NOT NULL,
    document_number VARCHAR(255),
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_size BIGINT,
    content_type VARCHAR(255),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    uploaded_by BIGINT,
    CONSTRAINT pk_employee_documents PRIMARY KEY (id)
);
